apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: login-service
  strategy: {}
  template:
    metadata:
      labels:
        app: login-service
    spec:
      containers:
        - env:
            - name: spring.datasource.url
              value: jdbc:mysql://login-db:3307/LOGIN_DB
            - name: eureka.client.service-url.defaultZone
              value: http://discovery-service:8761/eureka
            - name: eureka.client.register-with-eureka
              value: "true"
            - name: eureka.client.prefer-ip-address
              value: "true"
            - name: eureka.client.fetch-registry
              value: "true"
            - name: eureka.instance.hostName
              value: login-service
            - name: jwt.secret
              valueFrom:
                secretKeyRef:
                  name: galen-credentials
                  key: JWT_SECRET
          image: galenml/coding-challenge-login-service:latest
          name: login-service
          ports:
            - containerPort: 8083
          resources: {}
      restartPolicy: Always
